FROM golang:1.24 AS egts-builder

ENV GO111MODULE=on

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make

FROM busybox
ENV TZ=Europe/Moscow

COPY --from=egts-builder /app/bin /app/
COPY --from=egts-builder /app/configs/config.docker.test.yaml /etc/egts-receviver/config.yaml

ENTRYPOINT ["/app/receiver", "-c", "/etc/egts-receviver/config.yaml"]
