services:
  app:
    image: "${REGISTRY}/${IMAGE_OWNER}/${IMAGE_NAME}:${IMAGE_TAG}"
    env_file:
      - .env
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - app-logs:/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  app-logs:
