host: "0.0.0.0"
port: "7000"
conn_ttl: 5
log_level: "DEBUG"
log_file_path: "logs/app.log"
log_max_age_days: 366
# db_save_month_start: 5
# db_save_month_end: 9

storage:
  postgresql:
    host: "host.docker.internal"
    port: "5432"
    user: "postgres"
    password: "123"
    database: "egts"
    table: "point"
    packet_data_field_name: "packet_data"
    sslmode: disable