host: "127.0.0.1"
port: "7001"
conn_ttl: 5
log_level: "DEBUG"
log_file_path: "logs/app_test.log"
log_max_age_days: 1
# db_save_month_start: 5  # Month to start saving to DB (1=Jan, 12=Dec), inclusive. Default: 5 (May)
# db_save_month_end: 9    # Month to end saving to DB (1=Jan, 12=Dec), inclusive. Default: 9 (September)

storage:
  postgresql:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "123"
    database: "egts"
    table: "point"
    sslmode: disable
