host: "127.0.0.1"
port: "7000"
conn_ttl: 5
log_level: "DEBUG"
log_file_path: "logs/app.log"
log_max_age_days: 366

storage:
  postgresql:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "123"
    database: "egts"
    table: "point"
    sslmode: disable