host: "0.0.0.0"
port: "7000"
conn_ttl: 5
log_level: "DEBUG"
log_file_path: "logs/app.log"
log_max_age_days: 366
save_telematics_data_month_start: 5
save_telematics_data_month_end: 9

storage:
  host: "host.docker.internal"
  port: "5432"
  user: "postgres"
  password: "11062001"
  database: "egts"
  sslmode: require