host: "127.0.0.1"
port: "7000"
conn_ttl: 5
log_level: "DEBUG"
log_file_path: "logs/app.log"
log_max_age_days: 366
# db_save_month_start: 5  # Значение по умолчанию: 5 (Май)
# db_save_month_end: 9    # Значение по умолчанию: 9 (Сентябрь)

storage:
  postgresql:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "123"
    database: "egts"
    table: "point"
    sslmode: disable