host: "127.0.0.1"
port: "7000"
conn_ttl: 5
log_level: "DEBUG"

storage:
  postgresql:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "123"
    database: "egts"
    table: "point"
    sslmode: disable