host: "127.0.0.1"
ports:
  1: "7001"
connection_ttl: 5
log_level: "DEBUG"
log_file_path: "logs/app_test.log"
log_max_age_days: 1
save_telematics_data_month_start: 5
save_telematics_data_month_end: 9
optimize_geometry_cron_expression: "0 0 2 * * *"
migrations_path: "file://cli/receiver/migrations"

storage:
  driver: "postgres"
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "123"
  database: "egts"
  sslmode: disable
