host: "127.0.0.1"
port: "7001"
conn_ttl: 5
log_level: "DEBUG"
log_file_path: "logs/app_test.log"
log_max_age_days: 1
db_save_month_start: 5
db_save_month_end: 9

storage:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "123"
  database: "egts"
  sslmode: disable
