name: test-deploy

on:
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: egts-receiver
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: set-lowercase-owner
        run: echo "IMAGE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_SSH_KEY }}

      - name: trust-host
        run: ssh-keyscan -H ${{ secrets.TEST_HOST }} >> ~/.ssh/known_hosts

      - name: create-remote-context
        run: docker context create ci --docker "host=ssh://deploy@${{ secrets.TEST_HOST }}"

      - name: remote-login-ghcr
        run: docker --context ci login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}

      - name: compose-pull
        run: docker --context ci compose --env-file .env -f docker-compose.override.yml -f docker-compose.test.yml pull

      - name: compose-up
        run: docker --context ci compose --env-file .env -f docker-compose.override.yml -f docker-compose.test.yml up -d --pull always --force-recreate --remove-orphans

      - name: cleanup-context
        if: always()
        run: docker context rm -f ci
